### ISSUE TITLE
Instant Ban

### ISSUE THREAD

**Issue by ghost** [Griizz/Fortnite-Hack#6]
There was a new update. Just so everyone knows it is an instant ban. Play legit until its broken.

**Comment by psaidwid** [comment]
Hey I have created another option for changing the color of the esp for when a player is behind a wall and the color changes. They don't work exactly as intended and I tried to follow your code when creating the extra option although I have no idea how dx works and was wondering if you could fix them up too look good and include these changes in your next update.

[main.zip](https://github.com/Griizz/Fortnite-Hack/files/1366600/main.zip)

**Comment by tommy699** [comment]
can  u send me the dill file
